### ISSUE TITLE
Lower triangle matrices no longer work

### ISSUE THREAD

**Issue by tseemann** [khowe/quicktree#5]
I think somehting changed recently. Lower triangle PHYLIP distance matrices no longer work. I think this bug was introduced when you added code to handle sample IDs that look like numbers?

I think maybe the `for (j=0; j <= i; j++)` should be `j < i` maybe?

As the first sample of a LT Matrix has no numbers, just an ID ?

**Comment by khowe** [comment]
Fix included in release 2.3.
