### ISSUE TITLE
quicktree seems output wrong newick format

### ISSUE THREAD

**Issue by dukecomeback** [khowe/quicktree#9]
the wrong result (brackets not paired):
>(
hum_ENST00000314357.3:0.00000,
(
hum_ENST00000613448.2:0.00000,
(
hum_ENST00000646344.1:0.00000,
(
hum_ENST00000318124.3:0.00000,
hum_ENST00000642635.1:0.00000)
:0.00000)
)
:0.00000)
)
:0.00000)
);

the stockholm file:
>hum_ENST00000314357.3   -----------------MRIHYLLFALLF-----------------------------------------------LFLVPVPGHGGIINTLQKYYCRVRGGRCAVLSCLPKEEQIGKCSTRGRKCCRRKK
hum_ENST00000613448.2   -----------------MRIHYLLFALLF-----------------------------------------------LFLVPVPGHGGIINTLQKYYCRVRGGRCAVLSCLPKEEQIGKCSTRGRKCCRRKK
hum_ENST00000646344.1   -----------------MRIHYLLFALLF-----------------------------------------------LFLVPVPGHGGIINTLQKYYCRVRGGRCAVLSCLPKEEQIGKCSTRGRKCCRRKK
hum_ENST00000318124.3   -----------------MRIHYLLFALLF-----------------------------------------------LFLVPVPGHGGIINTLQKYYCRVRGGRCAVLSCLPKEEQIGKCSTRGRKCCRRKK
hum_ENST00000642635.1   -----------------MRIHYLLFALLF-----------------------------------------------LFLVPVPGHGGIINTLQKYYCRVRGGRCAVLSCLPKEEQIGKCSTRGRKCCRRKK

I used it with --upgma

**Comment by dukecomeback** [comment]
I guess it's because that the sequence are all the same? but still, if quicktree could give a tree in right format, that would be perfect for me.

**Comment by khowe** [comment]
Fixed in release 2.5. Thanks for reporting.
